name: Archive Changed CP Files

on:
  push:
    branches:
      - main

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set readable timestamp
        run: |
          TIME=$(date +"%Y-%m-%d_%I-%M%p")
          echo "NOW=$TIME" >> $GITHUB_ENV

      - name: Extract question name from commit message
        run: |
          MSG="${{ github.event.head_commit.message }}"
          NAME=$(echo "$MSG" | sed 's/ /-/g')
          echo "QUESTION_NAME=$NAME" >> $GITHUB_ENV

      - name: Clone archive repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/chandanSahoo-cs/cp-archive.git archive

      - name: Copy only changed .cpp files from onlineJudge
        run: |
          mkdir -p archive/
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^onlineJudge/.*\.cpp$' || true)
          for file in $CHANGED_FILES; do
            base=$(basename "$file")
            cp "$file" "archive/${QUESTION_NAME}_${NOW}_${base}"
          done

      - name: Commit and push to archive repo
        run: |
          cd archive
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Archived: $QUESTION_NAME at $NOW"
            git push
          fi
