name: Archive CP Solutions

on:
  push:
    branches:
      - main

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set timestamp
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Clone archive repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/chandanSahoo-cs/cp-archive.git archive

      - name: Copy all .cpp files and rename with original name + timestamp
        run: |
          mkdir -p archive/
          for file in onlineJudge/*.cpp; do
            if [ -f "$file" ]; then
              base=$(basename "$file" .cpp)
              cp "$file" "archive/${base}_$NOW.cpp"
            fi
          done

      - name: Commit and push to archive repo
        run: |
          cd archive
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Archived CP files at $NOW"
            git push
          fi
